# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromizedip',
            name='appear_date',
            field=models.CharField(max_length=20),
        ),
    ]
