# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_parse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromizedip',
            name='resourse',
            field=models.CharField(default=1, max_length=2555),
            preserve_default=False,
        ),
    ]
