# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:38
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ip_parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromized_ip',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
