# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_parse', '0002_compromizedip_resourse'),
        ('ip_parse', '0002_auto_20170223_0937'),
    ]

    operations = [
    ]
