# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_parse', '0003_merge_20170313_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromizedip',
            name='geom',
        ),
        migrations.AddField(
            model_name='compromizedip',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compromizedip',
            name='long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
