# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_parse', '0004_auto_20170313_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromizedip',
            name='appear_date',
            field=models.DateField(),
        ),
    ]
